### ISSUE TITLE
mirrorlist change in remi repository

### ISSUE THREAD

**Issue by kapouik** [linuxhq/ansible-role-remi#1]
Since two week, all mirrorlist must be on http://cdn.remirepo.net and no more on rpms.remirepo.net.

https://github.com/remicollet/remirepo/issues/95

**Comment by remicollet** [comment]
I also see some ref to famillecollet.com domain, which should be fixed to **remirepo.net** dedicated domain

**Comment by tkimball83** [comment]
Apologies, this issue slipped through the cracks and I missed it!

Anyhow, the mirrorlists and famillecollet issues have been sorted, and added an update for the remi2018 rpm gpg key.

I'm going to close this out, thanks!
